2021-01-24 18:15:08 INFO run.py:219 GNS3 server version 2.2.17
2021-01-24 18:15:08 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-01-24 18:15:08 INFO run.py:224 Config file /home/wtv/.config/GNS3/2.2/gns3_server.conf loaded
2021-01-24 18:15:08 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-01-24 18:15:08 INFO run.py:237 HTTP authentication is enabled with username 'admin'
2021-01-24 18:15:08 INFO run.py:243 Running with Python 3.9.1 and has PID 102864
2021-01-24 18:15:08 INFO run.py:79 Current locale is en_US.UTF-8
2021-01-24 18:15:08 INFO web_server.py:318 Starting server on localhost:3080
2021-01-24 18:15:08 INFO __init__.py:62 Load controller configuration file /home/wtv/.config/GNS3/2.2/gns3_controller.conf
2021-01-24 18:15:08 INFO __init__.py:66 Controller is starting
2021-01-24 18:15:08 INFO compute.py:64 Create compute local
2021-01-24 18:15:08 INFO compute.py:364 Connecting to compute 'local'
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:08 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-01-24 18:15:08 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/templates HTTP/1.1" 200 4342 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/appliances?symbol_theme=Classic HTTP/1.1" 200 737639 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:08 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:08 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-01-24 18:15:14 INFO project.py:78 Project f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd with path '/home/wtv/universidade/TPI/TPI_TP2' created
2021-01-24 18:15:14 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:14 +0000] "POST /v2/compute/projects HTTP/1.1" 201 302 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:14 INFO __init__.py:303 Creating new hypervisor localhost:39329 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:14 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', 'localhost:39329']
2021-01-24 18:15:14 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i1_stdout.txt
2021-01-24 18:15:14 INFO hypervisor.py:136 Dynamips process started PID=102887
2021-01-24 18:15:14 INFO __init__.py:305 Hypervisor localhost:39329 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:39329 after 0.4472 seconds
2021-01-24 18:15:15 INFO ethernet_switch.py:183 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977] has been created
2021-01-24 18:15:15 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:14 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ethernet_switch/nodes HTTP/1.1" 201 1561 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO __init__.py:303 Creating new hypervisor localhost:45463 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:15 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i2_log.txt', '-H', 'localhost:45463']
2021-01-24 18:15:15 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i2_stdout.txt
2021-01-24 18:15:15 INFO hypervisor.py:136 Dynamips process started PID=102904
2021-01-24 18:15:15 INFO __init__.py:305 Hypervisor localhost:45463 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:45463 after 0.0113 seconds
2021-01-24 18:15:15 INFO router.py:222 Router c3745 "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8] has been created
2021-01-24 18:15:15 INFO router.py:952 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: auto delete disks enabled
2021-01-24 18:15:15 INFO router.py:903 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: disk0 updated from 16MB to 0MB
2021-01-24 18:15:15 INFO router.py:661 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: idle-PC set to 0x0
2021-01-24 18:15:15 INFO router.py:489 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: has a new IOS image set: "/home/wtv/GNS3/images/IOS/c3745-advipservicesk9-mz.124-25d.image"
2021-01-24 18:15:15 INFO router.py:1027 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: MAC address updated from c401.91f8.0000 to c401.0991.0000
2021-01-24 18:15:15 INFO router.py:543 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: NVRAM updated from 304KB to 256KB
2021-01-24 18:15:15 INFO router.py:516 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: RAM updated from 128MB to 256MB
2021-01-24 18:15:15 INFO router.py:1102 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: adapter NM-1FE-TX inserted into slot 1
2021-01-24 18:15:15 INFO router.py:1102 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: adapter NM-1FE-TX inserted into slot 2
2021-01-24 18:15:15 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes HTTP/1.1" 201 1244 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO __init__.py:303 Creating new hypervisor localhost:41629 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:15 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i3_log.txt', '-H', 'localhost:41629']
2021-01-24 18:15:15 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i3_stdout.txt
2021-01-24 18:15:15 INFO hypervisor.py:136 Dynamips process started PID=102920
2021-01-24 18:15:15 INFO __init__.py:305 Hypervisor localhost:41629 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:41629 after 0.0124 seconds
2021-01-24 18:15:15 INFO router.py:222 Router c3745 "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb] has been created
2021-01-24 18:15:15 INFO router.py:952 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: auto delete disks enabled
2021-01-24 18:15:15 INFO router.py:903 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: disk0 updated from 16MB to 0MB
2021-01-24 18:15:15 INFO router.py:661 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: idle-PC set to 0x0
2021-01-24 18:15:15 INFO router.py:489 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: has a new IOS image set: "/home/wtv/GNS3/images/IOS/c3745-advipservicesk9-mz.124-25d.image"
2021-01-24 18:15:15 INFO router.py:1027 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: MAC address updated from c402.9208.0000 to c402.09d6.0000
2021-01-24 18:15:15 INFO router.py:543 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: NVRAM updated from 304KB to 256KB
2021-01-24 18:15:15 INFO router.py:516 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: RAM updated from 128MB to 256MB
2021-01-24 18:15:15 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes HTTP/1.1" 201 1230 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO __init__.py:303 Creating new hypervisor localhost:41703 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:15 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i4_log.txt', '-H', 'localhost:41703']
2021-01-24 18:15:15 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i4_stdout.txt
2021-01-24 18:15:15 INFO hypervisor.py:136 Dynamips process started PID=102936
2021-01-24 18:15:15 INFO __init__.py:305 Hypervisor localhost:41703 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:41703 after 0.0116 seconds
2021-01-24 18:15:15 INFO router.py:222 Router c3745 "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8] has been created
2021-01-24 18:15:15 INFO router.py:952 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: auto delete disks enabled
2021-01-24 18:15:15 INFO router.py:903 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: disk0 updated from 16MB to 0MB
2021-01-24 18:15:15 INFO router.py:489 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: has a new IOS image set: "/home/wtv/GNS3/images/IOS/c3745-advipservicesk9-mz.124-25d.image"
2021-01-24 18:15:15 INFO router.py:1027 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: MAC address updated from c403.9218.0000 to c403.09e8.0000
2021-01-24 18:15:15 INFO router.py:543 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: NVRAM updated from 304KB to 256KB
2021-01-24 18:15:15 INFO router.py:516 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: RAM updated from 128MB to 256MB
2021-01-24 18:15:15 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes HTTP/1.1" 201 1227 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO __init__.py:303 Creating new hypervisor localhost:40953 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:15 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i5_log.txt', '-H', 'localhost:40953']
2021-01-24 18:15:15 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i5_stdout.txt
2021-01-24 18:15:15 INFO hypervisor.py:136 Dynamips process started PID=102952
2021-01-24 18:15:15 INFO __init__.py:305 Hypervisor localhost:40953 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:40953 after 0.0113 seconds
2021-01-24 18:15:15 INFO router.py:222 Router c3745 "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b] has been created
2021-01-24 18:15:15 INFO router.py:952 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: auto delete disks enabled
2021-01-24 18:15:15 INFO router.py:903 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: disk0 updated from 16MB to 0MB
2021-01-24 18:15:15 INFO router.py:489 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: has a new IOS image set: "/home/wtv/GNS3/images/IOS/c3745-advipservicesk9-mz.124-25d.image"
2021-01-24 18:15:15 INFO router.py:1027 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: MAC address updated from c404.9228.0000 to c404.09fa.0000
2021-01-24 18:15:15 INFO router.py:543 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: NVRAM updated from 304KB to 256KB
2021-01-24 18:15:15 INFO router.py:516 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: RAM updated from 128MB to 256MB
2021-01-24 18:15:15 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes HTTP/1.1" 201 1227 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO __init__.py:303 Creating new hypervisor localhost:58371 with working directory /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips
2021-01-24 18:15:15 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i6_log.txt', '-H', 'localhost:58371']
2021-01-24 18:15:15 INFO hypervisor.py:129 Dynamips process logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dynamips_i6_stdout.txt
2021-01-24 18:15:15 INFO hypervisor.py:136 Dynamips process started PID=102968
2021-01-24 18:15:15 INFO __init__.py:305 Hypervisor localhost:58371 has successfully started
2021-01-24 18:15:15 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:58371 after 0.0117 seconds
2021-01-24 18:15:15 INFO router.py:222 Router c3745 "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1] has been created
2021-01-24 18:15:15 INFO router.py:952 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: auto delete disks enabled
2021-01-24 18:15:15 INFO router.py:903 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: disk0 updated from 16MB to 0MB
2021-01-24 18:15:15 INFO router.py:489 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: has a new IOS image set: "/home/wtv/GNS3/images/IOS/c3745-advipservicesk9-mz.124-25d.image"
2021-01-24 18:15:15 INFO router.py:1027 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: MAC address updated from c405.9238.0000 to c405.0a2f.0000
2021-01-24 18:15:15 INFO router.py:543 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: NVRAM updated from 304KB to 256KB
2021-01-24 18:15:15 INFO router.py:516 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: RAM updated from 128MB to 256MB
2021-01-24 18:15:15 INFO router.py:1102 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: adapter NM-1FE-TX inserted into slot 1
2021-01-24 18:15:15 INFO router.py:1102 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: adapter NM-1FE-TX inserted into slot 2
2021-01-24 18:15:15 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes HTTP/1.1" 201 1241 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:15 INFO docker_vm.py:1058 Docker container "ostinato-2" [e2fe7e02-616c-4331-97cc-e97daeab6a9a]: number of Ethernet adapters changed to 4
2021-01-24 18:15:16 INFO docker_vm.py:406 Docker container 'ostinato-2' [e2fe7e02-616c-4331-97cc-e97daeab6a9a] created
2021-01-24 18:15:16 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:15 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes HTTP/1.1" 201 933 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:16 INFO docker_vm.py:1058 Docker container "ostinato-3" [3e43c54e-3089-415c-b30d-693886dd2e73]: number of Ethernet adapters changed to 1
2021-01-24 18:15:16 INFO docker_vm.py:406 Docker container 'ostinato-3' [3e43c54e-3089-415c-b30d-693886dd2e73] created
2021-01-24 18:15:16 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:16 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes HTTP/1.1" 201 933 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:16 INFO docker_vm.py:1058 Docker container "ostinato-1" [ceb29d9d-3237-4366-9cc5-2488b768e9d0]: number of Ethernet adapters changed to 4
2021-01-24 18:15:17 INFO docker_vm.py:406 Docker container 'ostinato-1' [ceb29d9d-3237-4366-9cc5-2488b768e9d0] created
2021-01-24 18:15:17 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:16 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes HTTP/1.1" 201 933 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:17 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:17 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:17 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:17 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:17 INFO nio_udp.py:74 NIO UDP udp-63e935b4-1f6f-48c4-b504-fa82fc3d4aef created with lport=10000, rhost=127.0.0.1, rport=10001
2021-01-24 18:15:17 INFO base_node.py:655 Starting new uBridge hypervisor localhost:37283
2021-01-24 18:15:17 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:37283']
2021-01-24 18:15:17 INFO hypervisor.py:171 logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/dffc123b-80d2-488e-89ab-3a6be15245b8/ubridge.log
2021-01-24 18:15:17 INFO hypervisor.py:179 ubridge started PID=103051
2021-01-24 18:15:17 INFO base_node.py:658 Hypervisor localhost:37283 has successfully started
2021-01-24 18:15:17 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:37283 after 0.1017 seconds
2021-01-24 18:15:17 INFO router.py:1291 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: NIO udp-63e935b4-1f6f-48c4-b504-fa82fc3d4aef bound to port 0/0
2021-01-24 18:15:17 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:17 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/dffc123b-80d2-488e-89ab-3a6be15245b8/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:17 INFO nio_udp.py:74 NIO UDP udp-203458ac-6cdb-47fe-9bfa-bb3847446702 created with lport=10001, rhost=127.0.0.1, rport=10000
2021-01-24 18:15:17 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38647
2021-01-24 18:15:17 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:38647']
2021-01-24 18:15:17 INFO hypervisor.py:171 logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb/ubridge.log
2021-01-24 18:15:17 INFO hypervisor.py:179 ubridge started PID=103059
2021-01-24 18:15:17 INFO base_node.py:658 Hypervisor localhost:38647 has successfully started
2021-01-24 18:15:17 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38647 after 0.1022 seconds
2021-01-24 18:15:17 INFO router.py:1291 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: NIO udp-203458ac-6cdb-47fe-9bfa-bb3847446702 bound to port 0/0
2021-01-24 18:15:17 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:17 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-931ea929-b0f3-4461-8474-34315aa0bdd5 created with lport=10006, rhost=127.0.0.1, rport=10007
2021-01-24 18:15:18 INFO router.py:1291 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: NIO udp-931ea929-b0f3-4461-8474-34315aa0bdd5 bound to port 0/1
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/dffc123b-80d2-488e-89ab-3a6be15245b8/adapters/0/ports/1/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-b23aa74d-bf00-4e8d-a2d8-ee96fd4dac51 created with lport=10007, rhost=127.0.0.1, rport=10006
2021-01-24 18:15:18 INFO base_node.py:655 Starting new uBridge hypervisor localhost:43095
2021-01-24 18:15:18 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:43095']
2021-01-24 18:15:18 INFO hypervisor.py:171 logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/49957388-76c6-4f36-b09e-92fcbdd71aa8/ubridge.log
2021-01-24 18:15:18 INFO hypervisor.py:179 ubridge started PID=103068
2021-01-24 18:15:18 INFO base_node.py:658 Hypervisor localhost:43095 has successfully started
2021-01-24 18:15:18 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:43095 after 0.1017 seconds
2021-01-24 18:15:18 INFO router.py:1291 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: NIO udp-b23aa74d-bf00-4e8d-a2d8-ee96fd4dac51 bound to port 0/0
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/49957388-76c6-4f36-b09e-92fcbdd71aa8/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-79467210-81ec-4685-8b1c-4ddabf7cc9c5 created with lport=10012, rhost=127.0.0.1, rport=10013
2021-01-24 18:15:18 INFO router.py:1291 Router "R3" [49957388-76c6-4f36-b09e-92fcbdd71aa8]: NIO udp-79467210-81ec-4685-8b1c-4ddabf7cc9c5 bound to port 0/1
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/49957388-76c6-4f36-b09e-92fcbdd71aa8/adapters/0/ports/1/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-c9d692e1-7a13-49c5-b6a5-75ee02de2937 created with lport=10013, rhost=127.0.0.1, rport=10012
2021-01-24 18:15:18 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38463
2021-01-24 18:15:18 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:38463']
2021-01-24 18:15:18 INFO hypervisor.py:171 logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/76fd178a-4c4f-4b4e-9812-d711afaf7a9b/ubridge.log
2021-01-24 18:15:18 INFO hypervisor.py:179 ubridge started PID=103078
2021-01-24 18:15:18 INFO base_node.py:658 Hypervisor localhost:38463 has successfully started
2021-01-24 18:15:18 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38463 after 0.1018 seconds
2021-01-24 18:15:18 INFO router.py:1291 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: NIO udp-c9d692e1-7a13-49c5-b6a5-75ee02de2937 bound to port 0/0
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/76fd178a-4c4f-4b4e-9812-d711afaf7a9b/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-74671df4-a75e-456c-aafd-97846977f49e created with lport=10018, rhost=127.0.0.1, rport=10019
2021-01-24 18:15:18 INFO router.py:1291 Router "R2" [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: NIO udp-74671df4-a75e-456c-aafd-97846977f49e bound to port 0/1
2021-01-24 18:15:18 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb/adapters/0/ports/1/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:18 INFO nio_udp.py:74 NIO UDP udp-2c431aee-7bb5-44f0-858e-0fd1de8b5ef8 created with lport=10019, rhost=127.0.0.1, rport=10018
2021-01-24 18:15:18 INFO base_node.py:655 Starting new uBridge hypervisor localhost:43287
2021-01-24 18:15:18 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:43287']
2021-01-24 18:15:18 INFO hypervisor.py:171 logging to /home/wtv/universidade/TPI/TPI_TP2/project-files/dynamips/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/ubridge.log
2021-01-24 18:15:18 INFO hypervisor.py:179 ubridge started PID=103090
2021-01-24 18:15:18 INFO base_node.py:658 Hypervisor localhost:43287 has successfully started
2021-01-24 18:15:18 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:43287 after 0.1033 seconds
2021-01-24 18:15:18 INFO router.py:1291 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: NIO udp-2c431aee-7bb5-44f0-858e-0fd1de8b5ef8 bound to port 0/1
2021-01-24 18:15:18 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/adapters/0/ports/1/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:18 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO nio_udp.py:74 NIO UDP udp-8702f6b3-3efc-4fb8-866f-fe07cf627235 created with lport=10024, rhost=127.0.0.1, rport=10025
2021-01-24 18:15:19 INFO router.py:1291 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: NIO udp-8702f6b3-3efc-4fb8-866f-fe07cf627235 bound to port 1/0
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/adapters/1/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO ethernet_switch.py:271 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977]: NIO udp-8dffd663-2e54-4668-ac75-14fdc3f3e804 bound to port 0
2021-01-24 18:15:19 INFO ethernet_switch.py:361 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977]: port 0 set as an access port in VLAN 1
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ethernet_switch/nodes/83058438-0528-4bf5-a582-8f01fbb2c977/adapters/0/ports/0/nio HTTP/1.1" 201 389 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO ethernet_switch.py:271 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977]: NIO udp-64088efd-f749-4296-9b06-b41a0a7f2056 bound to port 2
2021-01-24 18:15:19 INFO ethernet_switch.py:361 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977]: port 2 set as an access port in VLAN 1
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ethernet_switch/nodes/83058438-0528-4bf5-a582-8f01fbb2c977/adapters/0/ports/2/nio HTTP/1.1" 201 389 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO docker_vm.py:960 Docker container 'ostinato-3' [3e43c54e-3089-415c-b30d-693886dd2e73]: NIO UDP added to adapter 0
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/3e43c54e-3089-415c-b30d-693886dd2e73/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO docker_vm.py:960 Docker container 'ostinato-2' [e2fe7e02-616c-4331-97cc-e97daeab6a9a]: NIO UDP added to adapter 0
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/e2fe7e02-616c-4331-97cc-e97daeab6a9a/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO nio_udp.py:74 NIO UDP udp-fa6b8a44-d468-4837-95d2-fdd838358c9c created with lport=10031, rhost=127.0.0.1, rport=10030
2021-01-24 18:15:19 INFO router.py:1291 Router "R1" [dffc123b-80d2-488e-89ab-3a6be15245b8]: NIO udp-fa6b8a44-d468-4837-95d2-fdd838358c9c bound to port 1/0
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/dffc123b-80d2-488e-89ab-3a6be15245b8/adapters/1/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO nio_udp.py:74 NIO UDP udp-3bd57a64-ebbf-4c9e-bcf8-f3d4076b9e5f created with lport=10034, rhost=127.0.0.1, rport=10035
2021-01-24 18:15:19 INFO router.py:1291 Router "R4" [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: NIO udp-3bd57a64-ebbf-4c9e-bcf8-f3d4076b9e5f bound to port 0/1
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/76fd178a-4c4f-4b4e-9812-d711afaf7a9b/adapters/0/ports/1/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO nio_udp.py:74 NIO UDP udp-163e9b6c-9361-4ba8-878e-b3fd9a3fe9f0 created with lport=10035, rhost=127.0.0.1, rport=10034
2021-01-24 18:15:19 INFO router.py:1291 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: NIO udp-163e9b6c-9361-4ba8-878e-b3fd9a3fe9f0 bound to port 0/0
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO nio_udp.py:74 NIO UDP udp-ab600c30-e27a-41e1-b866-9843a1d576dd created with lport=10040, rhost=127.0.0.1, rport=10041
2021-01-24 18:15:19 INFO router.py:1291 Router "R5" [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: NIO udp-ab600c30-e27a-41e1-b866-9843a1d576dd bound to port 2/0
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/adapters/2/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO docker_vm.py:960 Docker container 'ostinato-1' [ceb29d9d-3237-4366-9cc5-2488b768e9d0]: NIO UDP added to adapter 0
2021-01-24 18:15:19 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:15:19 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/ceb29d9d-3237-4366-9cc5-2488b768e9d0/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:14 +0000] "POST /v2/projects/load HTTP/1.1" 201 728 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:19 INFO project_handler.py:271 New client has connected to the notification stream for project ID 'f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd' (WebSocket method)
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "GET /v2/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/nodes HTTP/1.1" 200 28329 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "GET /v2/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/links HTTP/1.1" 200 11945 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:19 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:19 +0000] "GET /v2/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/drawings HTTP/1.1" 200 11071 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:24 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:24 +0000] "GET /v2/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/nodes/dffc123b-80d2-488e-89ab-3a6be15245b8/files/configs/i1_startup-config.cfg HTTP/1.1" 200 3175 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:15:28 INFO web_log.py:233 ::1 [24/Jan/2021:18:15:28 +0000] "GET /v2/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/files/configs/i5_startup-config.cfg HTTP/1.1" 200 2081 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:20:13 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:13 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:20:15 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:15 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:20:21 INFO notification_handler.py:82 Client has disconnected from controller WebSocket
2021-01-24 18:20:21 INFO server_handler.py:53 Start shutting down the server
2021-01-24 18:20:21 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/ethernet_switch/nodes/83058438-0528-4bf5-a582-8f01fbb2c977/stop HTTP/1.1" 204 255 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/dffc123b-80d2-488e-89ab-3a6be15245b8/stop HTTP/1.1" 204 248 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb/stop HTTP/1.1" 204 248 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/49957388-76c6-4f36-b09e-92fcbdd71aa8/stop HTTP/1.1" 204 248 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/76fd178a-4c4f-4b4e-9812-d711afaf7a9b/stop HTTP/1.1" 204 248 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/dynamips/nodes/f3d29728-0a31-4bd0-904e-99e09ad0cdc1/stop HTTP/1.1" 204 248 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:21 INFO docker_vm.py:533 Docker container 'ostinato-2' fix ownership, state = exited
2021-01-24 18:20:21 INFO docker_vm.py:533 Docker container 'ostinato-3' fix ownership, state = exited
2021-01-24 18:20:21 INFO docker_vm.py:533 Docker container 'ostinato-1' fix ownership, state = exited
2021-01-24 18:20:27 INFO docker_vm.py:793 Docker container 'ostinato-3' [ehlers/ostinato:latest] stopped
2021-01-24 18:20:27 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/3e43c54e-3089-415c-b30d-693886dd2e73/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:27 INFO docker_vm.py:793 Docker container 'ostinato-1' [ehlers/ostinato:latest] stopped
2021-01-24 18:20:27 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/ceb29d9d-3237-4366-9cc5-2488b768e9d0/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:27 INFO docker_vm.py:793 Docker container 'ostinato-2' [ehlers/ostinato:latest] stopped
2021-01-24 18:20:27 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/docker/nodes/e2fe7e02-616c-4331-97cc-e97daeab6a9a/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:27 INFO base_node.py:331 Dynamips: 'R3' [49957388-76c6-4f36-b09e-92fcbdd71aa8]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Dynamips: 'R5' [f3d29728-0a31-4bd0-904e-99e09ad0cdc1]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Docker: 'ostinato-1' [ceb29d9d-3237-4366-9cc5-2488b768e9d0]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Docker: 'ostinato-2' [e2fe7e02-616c-4331-97cc-e97daeab6a9a]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Docker: 'ostinato-3' [3e43c54e-3089-415c-b30d-693886dd2e73]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Dynamips: 'R1' [dffc123b-80d2-488e-89ab-3a6be15245b8]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Dynamips: 'R2' [b6f3a989-afd0-4f9d-a14f-cf3fddb4fcfb]: is closing
2021-01-24 18:20:27 INFO base_node.py:331 Dynamips: 'R4' [76fd178a-4c4f-4b4e-9812-d711afaf7a9b]: is closing
2021-01-24 18:20:27 INFO base_node.py:669 Stopping uBridge hypervisor localhost:43095
2021-01-24 18:20:27 INFO hypervisor.py:208 Stopping uBridge process PID=103068
2021-01-24 18:20:27 INFO base_node.py:669 Stopping uBridge hypervisor localhost:38463
2021-01-24 18:20:27 INFO hypervisor.py:208 Stopping uBridge process PID=103078
2021-01-24 18:20:27 INFO base_node.py:669 Stopping uBridge hypervisor localhost:38647
2021-01-24 18:20:27 INFO hypervisor.py:208 Stopping uBridge process PID=103059
2021-01-24 18:20:27 INFO base_node.py:669 Stopping uBridge hypervisor localhost:37283
2021-01-24 18:20:27 INFO hypervisor.py:208 Stopping uBridge process PID=103051
2021-01-24 18:20:27 INFO base_node.py:669 Stopping uBridge hypervisor localhost:43287
2021-01-24 18:20:27 INFO hypervisor.py:208 Stopping uBridge process PID=103090
2021-01-24 18:20:27 INFO docker_vm.py:872 Docker container 'ostinato-1' [ehlers/ostinato:latest] removed
2021-01-24 18:20:27 INFO ethernet_switch.py:248 Ethernet switch "Switch1" [83058438-0528-4bf5-a582-8f01fbb2c977] has been deleted
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102887
2021-01-24 18:20:27 INFO docker_vm.py:872 Docker container 'ostinato-2' [ehlers/ostinato:latest] removed
2021-01-24 18:20:27 INFO docker_vm.py:872 Docker container 'ostinato-3' [ehlers/ostinato:latest] removed
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102968
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102920
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102952
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102904
2021-01-24 18:20:27 INFO hypervisor.py:148 Stopping Dynamips process PID=102936
2021-01-24 18:20:28 INFO project.py:361 Project f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd with path '/home/wtv/universidade/TPI/TPI_TP2' closed
2021-01-24 18:20:28 INFO web_log.py:233 127.0.0.1 [24/Jan/2021:18:20:27 +0000] "POST /v2/compute/projects/f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd/close HTTP/1.1" 204 224 "-" "Python/3.9 aiohttp/3.6.2"
2021-01-24 18:20:28 INFO web_server.py:113 Closing 2 websocket connections...
2021-01-24 18:20:28 INFO web_log.py:233 ::1 [24/Jan/2021:18:20:21 +0000] "POST /v2/shutdown HTTP/1.1" 201 194 "-" "GNS3 QT Client v2.2.17"
2021-01-24 18:20:28 INFO project_handler.py:280 Client has disconnected from notification stream for project ID 'f6b10c95-1e21-4bd9-a42e-cc6e7cedd6dd' (WebSocket method)
2021-01-24 18:20:28 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-01-24 18:20:28 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2021-01-24 18:20:28 INFO __init__.py:130 Controller is stopping
2021-01-24 18:20:28 INFO run.py:272 Remove PID file /home/wtv/.config/GNS3/2.2/gns3_server.pid
